version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: controleanimais-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_animais
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: controleanimais-app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/app
    command: python main.py

volumes:
  mysql_data: